name: amongapp
description: "AI-Powered Lost & Found application with OTP-based authentication."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.14.0
  firebase_app_check: ^0.4.7
  firebase_auth: ^6.6.1
  cloud_functions: ^6.4.0
  http: ^1.2.0
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_messaging: ^16.6.0
  image_picker: ^1.2.3
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/placeholder_item.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
          weight: 400
        - asset: assets/fonts/LobsterTwo-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/LobsterTwo-Bold.ttf
          weight: 700
