// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

/// Firebase configuration generated by FlutterFire CLI.
///
/// Run `flutterfire configure` to regenerate this file with real values
/// for your Firebase project. The Android entry is populated from the
/// committed `google-services.json` so Android builds work out of the box.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase has not been configured for Linux. '
          'Run the FlutterFire CLI to configure this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android configuration from google-services.json.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbveD4ZUKOHdpiBZMOQR69A-Fc5MJFQWg',
    appId: '1:584709649247:android:61837035cf17c6af62bcea',
    messagingSenderId: '584709649247',
    projectId: 'firstfirebase-5880d',
    storageBucket: 'firstfirebase-5880d.firebasestorage.app',
  );

  // iOS configuration — run `flutterfire configure` to populate.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:584709649247:ios:94829722822ac25062bcea',
    messagingSenderId: '584709649247',
    projectId: 'firstfirebase-5880d',
    storageBucket: 'firstfirebase-5880d.firebasestorage.app',
  );

  // macOS configuration — run `flutterfire configure` to populate.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: '1:584709649247:ios:94829722822ac25062bcea',
    messagingSenderId: '584709649247',
    projectId: 'firstfirebase-5880d',
    storageBucket: 'firstfirebase-5880d.firebasestorage.app',
  );

  // Web configuration — run `flutterfire configure` to populate.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: '1:584709649247:web:a7303eaf4adf75de62bcea',
    messagingSenderId: '584709649247',
    projectId: 'firstfirebase-5880d',
    storageBucket: 'firstfirebase-5880d.firebasestorage.app',
  );

  // Windows configuration — run `flutterfire configure` to populate.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WINDOWS_API_KEY',
    appId: '1:584709649247:web:d2a1b160263a5d5062bcea',
    messagingSenderId: '584709649247',
    projectId: 'firstfirebase-5880d',
    storageBucket: 'firstfirebase-5880d.firebasestorage.app',
  );
}
